const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();if(file.endsWith('fanplay.html'))data=data.toString().replace('})();</script></body>',`window.fallbackForTest=getFallbackOptions;window.quoteForTest=FT.claimQuote;window.fxForTest=FTR_USD;window.setFixturesForTest=function(rows){matchesList=rows.map(normalizeMatch);renderMatchGrid();};window.selectionForTest=function(){return {player:selAsset&&selAsset.symbol,match:selMatch&&selMatch.id,market:selMarket&&selMarket.id,options:selOptionIds.length};};})();</script></body>`);res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('http://localhost:3001/**',r=>r.abort());await page.route('**/public/fantrade-supabase.js',r=>r.fulfill({contentType:'text/javascript',body:`window.FTDB={ready:()=>Promise.resolve(),signedIn:()=>false,snapshot:async()=>null,session:()=>null,board:async()=>({rows:[{id:'a',position:1,name:'North Bank',display_name:'Anna',handle:'anna',season_fp:980,value:5000,you:false},{id:'b',position:2,name:'Zero FC',display_name:'Test Fan',handle:'testfan',season_fp:800,value:3000,you:true},{id:'c',position:3,name:'City Lights',display_name:'Lee',handle:'lee',season_fp:760,value:4500,you:false}]})};`}));await page.addInitScript(()=>{if(!localStorage.getItem('fantrade_v1_state'))localStorage.setItem('fantrade_v1_state',JSON.stringify({auth:{signedIn:true},user:{name:'Test Fan',handle:'@testfan'},wallet:{balance:1000,locked:0},holdings:{FSAKA:{n:'Bukayo Saka',shares:100,avg:0.5,p:0.5,c:false},FHLND:{n:'Erling Haaland',shares:50,avg:0.5,p:0.5,c:false},FAITN:{n:'Aitana Bonmatí',shares:20,avg:0.5,p:0.5,c:false}}}));});const shots=path.join(root,'artifacts','premium');fs.mkdirSync(shots,{recursive:true});
try{
 await page.goto(base+'/fanplay.html');await page.waitForFunction(()=>window.setFixturesForTest);
 const quote=await page.evaluate(()=>quoteForTest({v:100000000,c:false,p:0},1));assert.equal(quote.usd,5000,'$100M player: 5% claim costs $5,000');assert.equal(quote.price*await page.evaluate(()=>fxForTest),0.01,'Single share is $0.01');
 const coachPicks=await page.evaluate(()=>fallbackForTest({name:'Mikel Arteta',type:'COACH',team:'Arsenal'}, {}, {}));
 assert(coachPicks.some(o=>o.evaluationRule.metric==='substitutions'),'Coach has substitution activities');
 assert(coachPicks.some(o=>o.evaluationRule.metric==='player_used'),'Coach has named player selection');
 assert(!coachPicks.some(o=>/scores a goal|records an assist|shots on target/.test(o.label)),'Coaches cannot receive personal player activities');
 await page.evaluate(()=>{document.getElementById('mLockedShares').textContent='340';document.getElementById('mActiveCount').textContent='4';document.getElementById('mProvFP').textContent='+57,950';});
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(100);assert(await page.locator('.fp-metric-lbl,.fp-metric-val').evaluateAll(items=>items.every(e=>getComputedStyle(e).whiteSpace==='nowrap'&&e.scrollWidth<=e.clientWidth+1)),'Summary stays single line without clipping at '+width);await page.screenshot({path:path.join(shots,'fanplay-summary-'+width+'.png'),fullPage:true});}

 await page.evaluate(()=>{const future=new Date(Date.now()+86400000).toISOString(),past=new Date(Date.now()-86400000).toISOString();setFixturesForTest([{id:'ars-home',homeTeam:'Arsenal FC',awayTeam:'Chelsea',scheduledAt:future,status:'SCHEDULED',competition:'Premier League'},{id:'ars-away',homeTeam:'Liverpool',awayTeam:'Arsenal',scheduledAt:future,status:'LINEUPS_CONFIRMED',competition:'Premier League'},{id:'city',homeTeam:'Man City',awayTeam:'Liverpool',scheduledAt:future,status:'SCHEDULED'},{id:'women',homeTeam:'Barcelona Women',awayTeam:'Chelsea Women',scheduledAt:future,status:'SCHEDULED'},{id:'closed',homeTeam:'Arsenal',awayTeam:'Chelsea',scheduledAt:future,cutoffTime:past,status:'SCHEDULED'},{id:'live',homeTeam:'Arsenal',awayTeam:'Chelsea',scheduledAt:future,status:'LIVE'}]);});
 await page.locator('#stepAssetGrid .fp-asset-card').filter({hasText:'Bukayo Saka'}).click();assert.equal(await page.locator('[data-fixture]').count(),2,'Only the selected player’s open home and away fixtures');assert(await page.locator('#fpMatchNext').isDisabled());
 await page.evaluate(()=>selectMatch('city'));assert.equal((await page.evaluate(()=>selectionForTest())).match,null,'Cannot choose another team fixture');
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)));await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(120);await page.screenshot({path:path.join(shots,'fanplay-'+width+'.png'),fullPage:true});}
 await page.locator('[data-fixture="ars-home"]').click();assert(await page.locator('#stepBox3').isVisible());await page.evaluate(()=>goToStep(1));await page.locator('#stepAssetGrid .fp-asset-card').filter({hasText:'Erling Haaland'}).click();assert.equal(await page.locator('[data-fixture]').count(),1);assert.equal((await page.evaluate(()=>selectionForTest())).market,null,'Changing player clears the old tier');assert.equal((await page.evaluate(()=>selectionForTest())).match,null,'Changing player clears old match');
 await page.evaluate(()=>goToStep(1));await page.locator('#stepAssetGrid .fp-asset-card').filter({hasText:'Aitana'}).click();assert.equal(await page.locator('[data-fixture="women"]').count(),1,'Women’s team fixtures stay separate');
 await page.evaluate(()=>setFixturesForTest([]));assert(await page.locator('.fp-fixture-empty').isVisible());assert(await page.locator('#fpMatchNext').isDisabled());await page.locator('.fp-fixture-empty button').click();assert(await page.locator('#stepBox1').isVisible());await page.evaluate(()=>resetWizard());assert(await page.locator('#stepBox1').isVisible());
 await page.goto(base+'/leaderboard.html');await page.waitForFunction(()=>document.getElementById('standingsSource').textContent==='Live club standings');assert.equal(await page.locator('.lb2-club').count(),3);assert.equal(await page.locator('#lb2List .lb2-row').count(),3,'Live standings replace preview field');assert.equal(await page.locator('#standingsMyRank').innerText(),'Rank #2');assert.equal(await page.locator('.lb2-rank.medal').count(),3,'Restore original medal ranks');assert.equal(await page.locator('.standings-podium,.standings-field,.standings-intro').count(),0,'New leaderboard sections are removed');await page.locator('#lb2SearchToggle').click();await page.locator('#standingsSearch').fill('Anna');assert.equal(await page.locator('#lb2List .lb2-row').count(),1);await page.locator('#lb2List .lb2-row').click();assert((await page.locator('#ftModalBackdrop').innerText()).includes('North Bank'));await page.locator('#ftModalClose').click();await page.locator('#standingsSearch').fill('');await page.locator('#lb2SearchToggle').click();assert.equal(await page.locator('#standingsMyValue').innerText(),'3,000','Your rank strip restores the club value');await page.locator('#lb2Division').click();await page.locator('[data-board-division="all"]').click();
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'Standings fit '+width);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(120);await page.screenshot({path:path.join(shots,'leaderboard-'+width+'.png'),fullPage:true});}
 await page.goto(base+'/dashboard.html');await page.locator('#homeClaimInput').fill('Victor Osimhen');await page.waitForTimeout(120);assert(await page.locator('.home-claim-row[data-claim]').count());for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(shots,'claim-'+width+'.png'),fullPage:true});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)));}assert((await page.locator('.activity-photo').first().evaluate(e=>getComputedStyle(e).borderRadius)).includes('24%'),'Rounded square player photos');
 await page.goto(base+'/wallet.html');assert.equal(await page.locator('.kc-wcard-art').count(),0);assert.equal(await page.locator('.wallet-balance-overview').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');const balance=await page.locator('#walBal').innerText();await page.locator('#walEyeBtn').click();assert((await page.locator('#walBal').innerText()).includes('•'));await page.locator('#walEyeBtn').click();assert.equal(await page.locator('#walBal').innerText(),balance);
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'Wallet fits '+width);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(120);await page.screenshot({path:path.join(shots,'wallet-'+width+'.png'),fullPage:true});}
 assert.deepEqual(errors,[]);console.log('Player fixtures, cutoff/status filtering, team aliases, reset/empty states, live standings/search and premium wallet passed at 4 widths');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
