const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const root=path.resolve(__dirname,'..'),shots=path.join(root,'artifacts','p2p');fs.mkdirSync(shots,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(f,(err,data)=>{if(err)return res.writeHead(404).end();if(f.endsWith('.html'))data=data.toString().replace('})();</script></body>','window.testFT=FT;})();</script></body>');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(f)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;
try{
 await page.route('**/public/fantrade-supabase.js',r=>r.fulfill({contentType:'text/javascript',body:'window.FTDB={ready:()=>Promise.resolve(),signedIn:()=>false};'}));await page.addInitScript(()=>{if(!localStorage.getItem('fantrade_v1_state'))localStorage.setItem('fantrade_v1_state',JSON.stringify({econV2:true,wallet:{balance:1000,locked:0},holdings:{}}));if(!localStorage.getItem('ft_market_v1'))localStorage.setItem('ft_market_v1',JSON.stringify({ftr_usd:2}));});
 await page.goto(base+'/buy.html?sim=off');await page.waitForFunction(()=>document.querySelectorAll('[data-trade]').length===3);assert((await page.locator('#p2pNotice').innerText()).includes('Demo P2P'));
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'P2P marketplace fits '+width);await page.screenshot({path:path.join(shots,'market-'+width+'.png'),fullPage:true});}
 await page.setViewportSize({width:390,height:900});await page.locator('[data-trade]').first().click();await page.locator('#p2pFiat').fill('100');assert.equal(await page.locator('#p2pReceive').innerText(),'50 $FTR');await page.locator('#p2pCheckout button[type=submit]').click();await page.waitForFunction(()=>!!document.querySelector('[data-action="PAID"]'));assert.equal(await page.evaluate(()=>testFT.getState().wallet.balance),1000,'Opening a buy never credits early');await page.locator('[data-action="PAID"]').click();await page.locator('#p2pConfirm input[type=checkbox]').check();await page.locator('#p2pConfirm button[type=submit]').click();await page.waitForFunction(()=>!!document.querySelector('[data-action="SIM_RELEASE"]'));assert.equal(await page.evaluate(()=>testFT.getState().wallet.balance),1000,'Marking paid never credits early');
 await page.locator('#p2pMessage').fill('<script>alert(1)</script>');await page.locator('#p2pMessageForm button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('p2pMessages').textContent.includes('<script>'));assert.equal(await page.locator('#p2pMessages script').count(),0,'Messages render as text');
 await page.locator('[data-action="SIM_RELEASE"]').click();await page.waitForFunction(()=>testFT.getState().wallet.balance===1050);assert((await page.locator('#p2pDialogBody').innerText()).includes('Completed'));await page.locator('#p2pClose').click();
 await page.locator('[data-view="SELL"]').click();await page.locator('[data-trade]').first().click();await page.locator('#p2pFiat').fill('100');for(const [name,value] of [['name','Demo Seller'],['provider','Demo Bank'],['account','DEMO-ONLY-123']])await page.locator('#p2pCheckout [name="'+name+'"]').fill(value);await page.locator('#p2pCheckout button[type=submit]').click();await page.waitForFunction(()=>!!document.querySelector('[data-action="SIM_PAID"]'));assert.equal(await page.evaluate(()=>testFT.getState().wallet.balance),1000);assert.equal(await page.evaluate(()=>testFT.getState().wallet.locked),50,'Sell order reserves FTR');await page.locator('[data-action="SIM_PAID"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-action="RELEASE"]'));
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(await page.locator('#p2pDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Order dialog fits '+width);await page.screenshot({path:path.join(shots,'order-'+width+'.png')});}
 await page.locator('[data-action="RELEASE"]').click();assert(await page.locator('#p2pConfirm input[type=checkbox]').isVisible());await page.locator('#p2pConfirm input[type=checkbox]').check();await page.locator('#p2pConfirm button[type=submit]').click();await page.waitForFunction(()=>testFT.getState().wallet.locked===0);assert.equal(await page.evaluate(()=>testFT.getState().wallet.balance),1000);await page.locator('#p2pClose').click();
 await page.locator('[data-view="BUY"]').click();await page.locator('[data-trade]').first().click();await page.locator('#p2pFiat').fill('20');await page.locator('#p2pCheckout button[type=submit]').click();await page.waitForFunction(()=>!!document.querySelector('[data-action="CANCEL"]'));await page.locator('[data-action="CANCEL"]').click();await page.locator('#p2pConfirm input[type=checkbox]').check();await page.locator('#p2pConfirm button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#p2pDialogBody .p2p-state').textContent==='Cancelled');await page.locator('#p2pClose').click();
 await page.locator('#p2pPost').click();for(const [name,value] of [['price','2'],['tokens','100'],['min','10'],['max','100'],['name','Demo Seller'],['provider','Demo Bank'],['account','DEMO-ONLY-123']])await page.locator('#p2pOfferForm [name="'+name+'"]').fill(value);await page.locator('#p2pOfferForm button[type=submit]').click();await page.waitForFunction(()=>testFT.getState().wallet.locked===100);assert.equal(await page.locator('[data-close-offer]').count(),1);await page.locator('[data-close-offer]').click();await page.locator('#p2pCloseOfferConfirm').click();await page.waitForFunction(()=>testFT.getState().wallet.locked===0);assert.equal(await page.evaluate(()=>testFT.getState().wallet.balance),1000,'Closing unused offer restores FTR');
 await page.goto(base+'/withdraw.html?sim=off');await page.waitForFunction(()=>document.querySelector('[data-view="SELL"]').getAttribute('aria-pressed')==='true');await page.locator('#p2pCurrency').click();await page.locator('[data-pick="NGN"]').click();await page.waitForFunction(()=>document.getElementById('p2pCurrency').textContent.includes('NGN'));await page.setViewportSize({width:320,height:900});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'NGN offers fit mobile');
 await page.evaluate(()=>localStorage.setItem('ft_market_v1',JSON.stringify({ftr_usd:0.07})));await page.goto(base+'/buy.html?sim=off');await page.waitForFunction(()=>document.querySelectorAll('[data-trade]').length===3);await page.locator('[data-trade]').first().click();await page.locator('#p2pFiat').fill('10.50');assert.equal(await page.locator('#p2pReceive').innerText(),'150 $FTR','Decimal quote uses exact minor-unit division');await page.locator('#p2pClose').click();
 // Authenticated errors must never fall back to demo offers or mint preview funds.
 const live=await browser.newPage();await live.route('**/public/fantrade-supabase.js',r=>r.fulfill({contentType:'text/javascript',body:'window.FTDB={ready:()=>Promise.resolve(),signedIn:()=>true,snapshot:async()=>null,call:async()=>{throw Error("P2P migration not installed");}};'}));await live.goto(base+'/buy.html');await live.waitForFunction(()=>document.getElementById('p2pStatus').textContent.includes('P2P is unavailable'));assert.equal(await live.locator('[data-trade]').count(),0);assert(await live.locator('#p2pPost').isDisabled());await live.close();
 const connected=await browser.newPage();connected.on('pageerror',e=>errors.push(e.message));await connected.route('**/public/fantrade-supabase.js',r=>r.fulfill({contentType:'text/javascript',body:`window.liveBalance=0;window.liveOrder=null;window.FTDB={ready:()=>Promise.resolve(),signedIn:()=>true,session:()=>null,snapshot:async()=>({wallet:{balance:liveBalance,locked:0},holdings:[],entries:[],transactions:[]}),call:async(fn,args)=>{if(fn==='ft_p2p_market')return {enabled:true,offers:[{id:'live-offer',name:'Live Trader',price:2,currency:'USD',available:100,min_fiat:10,max_fiat:100,method:'Bank transfer',completed:0}]};if(fn==='ft_p2p_mine')return {orders:liveOrder?[liveOrder]:[],offers:[]};if(fn==='ft_p2p_open'){liveOrder={id:'11111111-1111-4111-8111-111111111111',is_buyer:true,tokens:50,fiat:100,currency:'USD',method:'Bank transfer',payment_details:{name:'Seller',provider:'Bank',account:'TEST-ONLY'},status:'AWAITING_PAYMENT',expires_at:new Date(Date.now()+1200000).toISOString(),created_at:new Date().toISOString(),messages:[]};return liveOrder;}if(fn==='ft_p2p_action'){liveOrder.status='PAID';return liveOrder;}throw Error('Unexpected operation');}};`}));await connected.goto(base+'/buy.html');await connected.waitForFunction(()=>document.querySelectorAll('[data-trade]').length===1);assert(!(await connected.locator('#p2pNotice').innerText()).includes('Demo'));
 await connected.locator('[data-trade]').click();await connected.locator('#p2pFiat').fill('100');await connected.locator('#p2pCheckout button[type=submit]').click();await connected.waitForFunction(()=>!!document.querySelector('[data-action="PAID"]'));await connected.locator('[data-action="PAID"]').click();await connected.locator('#p2pConfirm input[type=checkbox]').check();await connected.locator('#p2pConfirm button[type=submit]').click();await connected.waitForFunction(()=>document.querySelector('#p2pDialogBody .p2p-state').textContent.includes('Payment sent'));assert.equal(await connected.locator('[data-action="SIM_RELEASE"]').count(),0,'Real buyers cannot simulate escrow release');
 await connected.evaluate(()=>{liveOrder.status='COMPLETED';liveBalance=50;dispatchEvent(new Event('focus'));});await connected.waitForFunction(()=>testFT.getState().wallet.balance===50);assert((await connected.locator('#p2pDialogBody').innerText()).includes('Completed'),'Remote seller release refreshes the buyer order and wallet');await connected.close();
 assert.deepEqual(errors,[]);console.log('P2P browser checks passed: responsive Buy/Sell, private payment instructions, payment/release confirmations, escrow accounting, cancellation, offer lifecycle, safe messages, global currency picker and no live demo fallback.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
